name: CI

on:
  push:
    branches: [master]
  pull_request: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node toolchain
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Cache PureScript dependencies
        uses: actions/cache@v3
        with:
          path: |
            .spago
            output
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM dependencies
        run: npm install

      - name: Build the project
        run: npm run build-ci

      - name: Run the tests
        run: npm run test
